# Generated by Django 4.2 on 2023-07-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='body_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
